> ⚠️ **Atenção:**  
> Vocês podem colaborar, discutir ideias e aprender juntos.  
> No entanto, **cada estudante deve elaborar e entregar sua própria solução**.  
> Qualquer trabalho feito com auxílio de Inteligência Artificial (IA) será **anulado** e a nota atribuída será **zero**.  


In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# NumPy

## Exercício 1
Crie um vetor com 20 números inteiros aleatórios entre 0 e 100.  
- Mostre o vetor.  
- Calcule média, desvio-padrão e valor máximo.  

In [24]:
vec = np.random.choice(100, size = 20)
print(vec)
media = np.mean(vec)
print(f'Média: {media}')
std = np.std(vec)
print(f'Desvio padrão: {std.round(2)}')
maximo = np.max(vec)
print(f'Valor maximo: {maximo}')


[10 73 99 84 79 80 62 25  1 75 77 57 26 33 68 33  8  2 76 84]
Média: 52.6
Desvio padrão: 31.02
Valor maximo: 99


## Exercício 2
Gere uma matriz $5 \times 5$ com valores da distribuição normal padrão.  
- Calcule a soma de cada linha e de cada coluna.  
- Extraia a diagonal principal.  

In [32]:
norm = np.random.normal(0,1,(5,5))
print(norm)
np.sum(norm, axis = 1)

[[ 1.71635923 -0.48551802  0.14151401  0.96545406  0.53432186]
 [ 2.21053727  0.9632134  -0.42967133 -1.58870412  0.49348314]
 [ 0.49850906  0.44277466  1.92536468 -0.50504647  0.26377714]
 [-0.48203516  0.42570977  1.80975342 -1.05289287 -0.65016782]
 [ 0.53675632  0.08702648 -0.66418291 -1.10077944 -0.91074581]]


array([ 2.87213114,  1.64885837,  2.62537907,  0.05036733, -2.05192535])

## Exercício 3
Implemente uma função que recebe dois vetores NumPy e retorna:  
- Produto escalar (`np.dot`).  
- Distância euclidiana entre eles (`np.linalg.norm`).  

## Exercício 4
Crie uma matriz quadrada $A \in \mathbb{R}^{4 \times 4}$ com valores inteiros aleatórios entre $-5$ e $5$.  
- Verifique se $A$ é invertível calculando $\det(A)$ (`np.linalg.det`).  
- Caso seja, calcule $A^{-1}$ (`np.linalg.inv`) e verifique se $A \cdot A^{-1} = I$.  

## Exercício 5
Gere uma matriz simétrica $B \in \mathbb{R}^{5 \times 5}$ a partir de uma matriz aleatória $M$ definida por $B = \tfrac{1}{2}(M + M^T)$.  
- Calcule os autovalores e autovetores (`np.linalg.eig`).  
- Verifique numericamente a relação $Bv = \lambda v$.  

## Exercício 6
Considere um sistema linear $Ax = y$, com $A \in \mathbb{R}^{3 \times 3}$ e $y \in \mathbb{R}^3$.  
- Gere $A$ de forma aleatória e $y$ como um vetor de inteiros.  
- Resolva o sistema (`np.linalg.solve`).  
- Verifique a solução computando $\|Ax - y\|_2$ (`np.linalg.norm`).  

## Exercício 7
Simule 100 vetores bidimensionais com distribuição normal padrão e forme a matriz de covariância empírica $S$.  
- Calcule a matriz de covariância (`np.cov`).  
- Encontre os autovalores e autovetores de $S$ (`np.linalg.eig`).  
- Mostre que os autovetores correspondem às direções principais da variabilidade dos dados.  

# Pandas

## Exercício 1
Leia um arquivo CSV de exemplo (ex: `iris.csv`).  
- Carregue o arquivo (`pd.read_csv`).  
- Mostre as primeiras 5 linhas (`df.head`).  
- Verifique tipos de dados e valores ausentes (`df.info`, `df.isna`).  

## Exercício 2
Carregue novamente o `iris.csv` e:  
- Calcule a média e o desvio-padrão do comprimento da pétala por espécie (`df.groupby`, `agg`).  
- Ordene os resultados pela média.  

## Exercício 3
Crie um novo DataFrame a partir de um dicionário Python com 3 colunas: `nome`, `idade` e `cidade`.  
- Adicione uma nova coluna com a idade ao quadrado (`df['col'] = ...`).  
- Exclua essa coluna depois (`df.drop`).  

## Exercício 4
Filtre um DataFrame para mostrar apenas as linhas em que a coluna `idade` seja maior que 30 (`df.query` ou `df[df['idade'] > 30]`).  
- Conte quantas linhas satisfazem essa condição (`len`, `df.shape`).  

## Exercício 5
Considere um DataFrame com notas de alunos em diferentes disciplinas.  
- Calcule a média de cada aluno (`df.mean(axis=1)`).  
- Calcule a média por disciplina (`df.mean(axis=0)`).  
- Identifique o aluno com a maior nota média (`df.idxmax`).  

## Exercício 6
Carregue novamente o `iris.csv`.  
- Selecione apenas as colunas de comprimento e largura da pétala (`df[['col1', 'col2']]`).  
- Normalize os valores dessas colunas para o intervalo $[0,1]$ (`df.apply`).  

## Exercício 7
Simule um DataFrame de vendas com colunas `produto`, `preço` e `quantidade`.  
- Crie uma nova coluna `receita = preço * quantidade`.  
- Agrupe por produto e calcule a receita total (`df.groupby`, `sum`).  
- Ordene os produtos do mais vendido para o menos vendido.  

## Exercício 8
Carregue novamente o `iris.csv`.  
- Exporte apenas as linhas da espécie *setosa* para um novo CSV (`df.to_csv`).  
- Leia o arquivo de volta (`pd.read_csv`) e verifique se o número de linhas bate (`len`).  


# Pandas

## Exercício 1
Leia o arquivo `iris.csv`.  
- Carregue o arquivo (`pd.read_csv`).  
- Mostre as primeiras 5 linhas (`df.head`).  
- Verifique tipos de dados e valores ausentes (`df.info`, `df.isna`).  

## Exercício 2
Calcule estatísticas descritivas do dataset.  
- Média, desvio-padrão, mínimo e máximo de cada coluna numérica (`df.describe`).  

## Exercício 3
Agrupe por `variety`.  
- Calcule a média e o desvio-padrão da coluna `petal.length` (`df.groupby`, `agg`).  
- Ordene os resultados pela média.  

## Exercício 4
Selecione apenas as colunas `petal.length` e `petal.width`.  
- Crie um novo DataFrame com essas colunas (`df[['col1', 'col2']]`).  
- Normalize os valores dessas colunas para o intervalo $[0,1]$ (`df.apply`).  

## Exercício 5
Filtre o DataFrame.  
- Mostre apenas as linhas da variedade *Setosa* (`df.query`).  
- Conte quantas observações existem dessa variedade (`len`).  

## Exercício 6
Exporte e leia de volta.  
- Salve apenas as linhas da variedade *Versicolor* em um novo CSV (`df.to_csv`).  
- Leia o arquivo de volta (`pd.read_csv`) e verifique o número de linhas.  

## Exercício 7
Ordene e filtre com múltiplas condições.  
- Selecione apenas as observações com `sepal.length` maior que 6 e variedade diferente de *Virginica* (`df.query`).  
- Ordene as linhas resultantes pela coluna `petal.length` (`df.sort_values`).  


# Matplotlib

## Exercício 1
Carregue o dataset `iris.csv` com Pandas.  
- Plote um histograma da coluna `sepal.length` (`plt.hist`).  
- Adicione título e rótulos nos eixos (`plt.title`, `plt.xlabel`, `plt.ylabel`).  

## Exercício 2
Crie um gráfico de dispersão (`plt.scatter`) entre `sepal.length` e `sepal.width`.  
- Diferencie as variedades (`variety`) por cores.  
- Adicione legenda (`plt.legend`).  

## Exercício 3
Faça um gráfico de dispersão entre `petal.length` e `petal.width`.  
- Use tamanhos de pontos proporcionais a `sepal.length` (`s=` no `plt.scatter`).  
- Adicione rótulos de eixos e título.  

## Exercício 4
Crie **3 histogramas lado a lado** mostrando a distribuição de `petal.length` para cada variedade.  
- Use `plt.subplot` para organizar os gráficos.  
- Coloque títulos individuais em cada histograma.  

## Exercício 5
Plote boxplots (`plt.boxplot`) das colunas `sepal.length`, `sepal.width`, `petal.length` e `petal.width`.  
- Use rótulos (`labels=`).  
- Interprete qual característica tem maior variabilidade.  

## Exercício 6
Plote as médias das 4 medidas (`sepal.length`, `sepal.width`, `petal.length`, `petal.width`) para cada variedade em um gráfico de barras.  
- Use `df.groupby` para calcular as médias.  
- Plote usando `plt.bar` ou `plt.barh`.  

## Exercício 7
Faça um gráfico de dispersão 3D entre `sepal.length`, `sepal.width` e `petal.length`.  
- Use `mpl_toolkits.mplot3d.Axes3D` com `ax.scatter`.  
- Diferencie as variedades por cor.  
